### ISSUE TITLE
what about emacsclient

### ISSUE THREAD

**Issue by pushqrdx** [probonopd/Emacs.AppImage#14]
I usually run emacs as daemon and use emacsclient, is there a way to achieve this with this appimage?

**Comment by probonopd** [comment]
Have you tried running the AppImage with the `--daemon` argument?

**Comment by pushqrdx** [comment]
@probonopd but this takes care of the daemon part, how can i reach emacsclient binary itself then?

**Comment by probonopd** [comment]
Sorry I don't know about `emacsclient`. If something like `emacs --client` exists, then running the AppImage with `--client` should work. If it is a separate binary then an AppImage could probably be made for it.

It would be best if the Emacs authors would provide an officially made, tested, and supported AppImage of it. I really don't know much about Emacs myself. Sorry I can't be of more help here.

**Comment by pushqrdx** [comment]
@probonopd thanks for your help anyways, yeah emacsclient is the binary you use to connect to existing emacs daemon it's a part of the emacs package, you can see it in the appimage next to emacs's binary, itdoesn't execute emacs but rather act as a client side interface.
