### ISSUE TITLE
Build with gtk3 toolkit

### ISSUE THREAD

**Issue by favadi** [probonopd/Emacs.AppImage#2]
Hi, any reason you build this with gtk2 instead of gtk3? In my case, gtk2 tool kit doesn't work well with HiDPI screen, so gtk3 is better.

**Comment by probonopd** [comment]
I think gtk2 is more common (every distro supports it out-of-the box).

But you're welcome to send a pull request that builds it with gtk3.

**Comment by favadi** [comment]
I modify the build script to compile with gtk3, it seems to work fine. You can download to the binary [here](https://transfer.sh/8yXgA/emacs-25.1-glibc2.17-x86-64.appimage).

**Comment by favadi** [comment]
The PR #3.

**Comment by favadi** [comment]
Actually after use it for few minutes, there are something weird about font size. Please don't merge my MR, I'm investigating.

**Comment by favadi** [comment]
The weird font rendering problem is fixed when I disable xwidgets and cairo support, this [binary](https://transfer.sh/9yd4j/emacs-25.1-glibc2.17-x86-64.appimage) works fine.

**Comment by probonopd** [comment]
@favadi forgive me for what may be a stupid question, are there actual advantages for the user, besides having a higher version number?

Your binary works for me.

**Comment by favadi** [comment]
Gtk2 doesn't support HiDPI, in my case with scaling factor = 2, the 
toolbar, scrollbar, menubar all look tiny. Compile with gtk3 fix it.

**Comment by probonopd** [comment]
> Gtk2 doesn't support HiDPI, in my case with scaling factor = 2, the toolbar, scrollbar, menubar all look tiny. Compile with gtk3 fix it.

That's a good use case for sure.

**Comment by probonopd** [comment]
Thanks @favadi, merged code and added to Releases page.
