### ISSUE TITLE
symbol lookup error on Fedora

### ISSUE THREAD

**Issue by manuq** [probonopd/Emacs.AppImage#4]
Trying to run the AppImage, I get this error on Fedora 27:
```
/tmp/.mount_GNU_EmT9JNu6/usr/bin/emacs: symbol lookup error: /lib64/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates
```
Looks like the same issue reported in https://github.com/probonopd/linuxdeployqt/issues/157 .

**Comment by probonopd** [comment]
Does this happen with both AppImages?

**Comment by manuq** [comment]
@probonopd I just tried with `GNU_Emacs-25.2.glibc2.15-x86_64.AppImage`, which other AppImage do you mean?

**Comment by probonopd** [comment]
There are two AppImages listed on https://github.com/probonopd/Emacs.AppImage/releases.

**Comment by manuq** [comment]
@probonopd those two are working like a charm. I was trying with another one, found in the table "My AppImages at Bintray" here https://fusion809.github.io/appimages/

Thanks for the package! Closing this ticket.
