### ISSUE TITLE
emacs.appimage unpack failure

### ISSUE THREAD

**Issue by shiptux** [probonopd/Emacs.AppImage#5]
Mr.probonopd:
     I am very interested in the process of packing emacs, because i try to pack a lispbox.appimage ,lisp in a box project stopped developing in 2011, so i try to DIY.This the error message.
trv.path: usr/share/emacs/25.1/lisp/COPYING
sqfs_inode_id: 634131935
inode.base.inode_type: 2
inode.xtra.reg.file_size: 35147
Extract to: squashfs-root/usr/share/emacs/25.1/lisp/COPYING
fopen error
When unpacking here will error.

**Comment by probonopd** [comment]
This has since been fixed in AppImageKit but the Emacs AppImage has not been updated yet to use the new AppImageKit code. To extract this AppImage, you can do:

```
wget -c https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
wget -c https://github.com/probonopd/Emacs.AppImage/releases/download/AppImage/Emacs-25.1-glibc2.17-x86-64.AppImage
chmod +x *.AppImage
TARGET_APPIMAGE=Emacs-25.1-glibc2.17-x86-64.AppImage ./appimagetool-x86_64.AppImage --appimage-extract
```
