### ISSUE TITLE
Cannot open doc string file "DOC"

### ISSUE THREAD

**Issue by zot** [probonopd/Emacs.AppImage#9]
When I do C-h f on a built-in function (like cons, for instance), I get this error. I'm guessing it's a configuration problem with the AppImage. I've been using a deb for a while because of this but I really prefer to use AppImages as much as possible!

**Comment by probonopd** [comment]
Do you know what configuration would need to be changed? I am not an Emacs user myself at all, sorry.

**Comment by zot** [comment]
Not sure -- I'll see if I can check it out in the next few days...

**Comment by zot** [comment]
Looks like the emacs variable "doc-directory" is supposed to be
```
/tmp/.mount_Emacs-MQFIoI/usr/share/emacs/26.1/etc
```
but the value is
```
/tmp/.mount_Emacs-MQFIoI/usr/share/emacs/26.1//etc/DOC-26.1/
```
which doesn't exist.

The DOC file says of doc-directory: "Directory containing the DOC file that comes with GNU Emacs.
This is usually the same as `data-directory'." It's not though, data-directory looks to be correct.

Hmm, AppRun has this line in it:

```
export EMACSDOC=$EMACSPATH/etc/DOC-$VER
```

I'm guessing it should be:

```
export EMACSDOC=$EMACSPATH/etc
```

**Comment by zot** [comment]
To test it, just do `C-h f` and type `cons` (then hit enter). In the current AppImage, you'll see the error:
```
cons is a built-in function in ‘C source code’.

(cons ARG1 ARG2)

Cannot open doc string file "DOC"
```
What you ought to see is this:
```
cons is a built-in function in ‘C source code’.

(cons CAR CDR)

Create a new cons, give it CAR and CDR as components, and return it.
```
